# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c496755bdce9c3d57ae6c1e1b666b4b028cea5c7cbdba30e73310182a789d1a1fd111e16c6cde60403b92cb0dd7932e427b4f3eb31bd3b2575c8d42480d6d670

test:
  secret_key_base: d8a78d67030448a8f825d9506802580f8f55f00ad35c726f8504733b7d34c7e9e71287cbcb9abf01018532a33253facb490f830ed71ffffede0400bd98525814

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
